@startuml
!include ../include/diagram-style.puml

title Add New Trail

actor "End User" as EU
boundary SearchPanel
boundary TrailPanel
control TrailService
database Database

EU -> SearchPanel : click "New Trail"
EU -> SearchPanel : enter name, length, elevation
SearchPanel -> SearchPanel : nextTrailId()
SearchPanel -> TrailService : createTrail(name, id, length, elevation)
TrailService -> Database : insertTrail(trail)
Database -> Database : save()
Database --> TrailService : ok
TrailService --> SearchPanel : ok

SearchPanel --> EU : list refreshes (new trail)

' Optional: add photos from trail detail view
opt add photos later
  EU -> TrailPanel : open trail, "Add Trail Image"
  TrailPanel -> TrailService : saveTrail()
  TrailService -> Database : save()
end

@enduml
